name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build DotNet
        uses: Elskom/build-dotnet@v1.1.1
        with:
          # Filepath of the solution of which contains all the projects to be built, optionally tested and packed, relative to root of repository
          SOLUTION_FILE_PATH: SysMatur.sln
          PATH: false
